sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        BVOfB+XCCXpecw7JA84aJWFO9CSapb+DY8FdDLWmnROZAojQq3h8lSAMFA6jPCkxSuWUMk31q83mZZEN0D9qTV3uTc+6c6/bhR5e7Fou7bcQQyreugRBmtUm4TRBc08iX5Gyb/bo25KHkSxxC86SH4IscicQzxoxejzXzIzFXSEuldC+RkKZx6pcaCm59I1DoIb8OSg/OuJVzxkLz/xGgJ+daCr1vvICbxkB2YxWulf4ge8OY45PpO1ZO113PWYuIm+61NEWPQa8sEtn4USVsahU+YLbEzS7viewKoYY6UZNB8DEObBM55116xAOtJ7TAuOAkiuUO6wGtQKo5VWzPHzO9830ZG593XrEHw0vjZSghKnSusgRC/ujFdAA37Mv7N0g+u4s+muP54CQcSJPqZVD6g6BRwEU3YCizX8yQxp4+FrLz5TpO4FuMgk3GU4p6FcPl6o/qE9yLQJUy/+aF9yF6/VWXZYqBDe9Tk/ZjA3BjW+c8IwPny6llt+OfER0+HwHdLTlW0iCgrFLfSauMkwJhh8hP/hyoHYQjVXwMcjDL7q8nHj00UWHFT97Mlq+SUs6fDqVje7wurMvKx+xZJvoGhuSRKLOD5YWN6O4R3hPBI+Pn05vWAGRUzs0Q/GNRBLANmOHwAUrIp6eypj56GsgBkoVC+/avB3TBI1mqk8=
    - secure: >-
        U7h/7MggYGK46U+vSMBI/WyKdsUyV+g1wDItlB0vd+2NvG6mYteU6TJpRsZ4wrDjD1v0UWC9DsGyRgNrkmpaN3ZXr1ro0QES11EASzBf2G/dG2Ri1rWQOm2Kj+OIk9OCKFHA57rqMEk0phQbUKMZFUqmOJMym+1p1ou3QEnpYMJZpAyBhPdwO0Uvpb4XlR4wIFI6ZnWgXwaJ05EM9EdpkjjRucTSgKW3h4PydocVu1ltqguxaNGreYywEbguYeczmZAhFmauTWWjm1Nw2eNN1bd+WU/29PZit56CshvIkAR+ioin+G1N/i7wtML/e7K6kkzoHC4/ApjfRdIGoW6tfAglT8YSozu2fBC/2nHribK88Ea9ONy0v5BQOaOP3a1wrOkpRDtQSbCz2uNkhN1mHp1nZe2fzCAWYC20wExkq8618NU1HTnLRxeTMyvcbDyui05nGtB9zUGGO3zUfC1a5JMv2LE2d7p0TIrBgYrpZ7H4T2Bm/sKuTD8Vx5D0l7ciRuQh30e0mAqVXnO9umoyOHaks2ctQdX0MVgWVGxTYiHYtLfoEhW50OEuxBnchIBcxu09mw3XCUh8AbAbErE5Qu386MgGjlYTV35/7sdFFJQdycFAagweG1tPakgRXVUGhIiAxAcxvE+GfLi13J0EWhQQuyuzxxezTHTu/Eb+XMg=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
